CREATE DATABASE PROYECTO_VISITAHAL;

CREATE TABLE SERVICIO(
idServicio int AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(50),
descripcion VARCHAR(100)
);

CREATE TABLE ROL(
idRol int AUTO_INCREMENT PRIMARY KEY,
tipo VARCHAR(50)
);

CREATE TABLE ALOJAMIENTO(
idAlojamiento int AUTO_INCREMENT  PRIMARY KEY,
tipo varchar(50)
);

CREATE TABLE USUARIO (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    DNI VARCHAR(9) UNIQUE,
    correoElectronico VARCHAR(30) UNIQUE,
    contrasenna VARCHAR(400),
    nombre VARCHAR(30),
    apellidos VARCHAR(50), 
    CP CHAR(5),
    idRol INT,
    FOREIGN KEY (idRol) REFERENCES ROL(idRol)
    ON DELETE RESTRICT ON UPDATE RESTRICT
);


CREATE TABLE CONTRATA(
idServicio int,
idUsuario int,
fechaContrata DATE,
PRIMARY KEY(idServicio, idUsuario, fechaContrata),
FOREIGN KEY(idServicio) REFERENCES SERVICIO (idServicio)
ON DELETE RESTRICT ON UPDATE RESTRICT,
FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario)
ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE RESERVA(
idUsuario int,
idAlojamiento int,
fechaReserva DATE,
PRIMARY KEY(idUsuario, idAlojamiento, fechaReserva),
FOREIGN KEY (idAlojamiento) REFERENCES ALOJAMIENTO(idAlojamiento)
ON DELETE RESTRICT ON UPDATE RESTRICT,
FOREIGN KEY (idUsuario) REFERENCES USUARIO (idUsuario)
ON DELETE RESTRICT ON UPDATE RESTRICT
);
